2025-04-06 02:04:00,541 [ERROR] in app: ѕроизошла ошибка: Parent instance <Cargo at 0x22b38c6f800> is not bound to a Session; lazy load operation of attribute 'train' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 84, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 277, in cargo_list
    return render_template('cargo_list.html', cargos=cargos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\Python312\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\SystemX\Documents\проекты\логистика\templates\cargo_list.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\SystemX\Documents\проекты\логистика\templates\base.html", line 73, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\templates\cargo_list.html", line 30, in block 'content'
    {% if c.train %}
  File "c:\Python312\Lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\sqlalchemy\orm\attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\sqlalchemy\orm\strategies.py", line 922, in _load_for_state
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Cargo at 0x22b38c6f800> is not bound to a Session; lazy load operation of attribute 'train' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-04-06 02:08:02,794 [ERROR] in app: ѕроизошла ошибка: name 'joinedload' is not defined
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 84, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 276, in cargo_list
    cargos = db.query(Cargo).options(joinedload(Cargo.train)).all()
                                     ^^^^^^^^^^
NameError: name 'joinedload' is not defined
2025-04-06 02:08:27,053 [ERROR] in app: ѕроизошла ошибка: name 'joinedload' is not defined
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 84, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\Documents\проекты\логистика\app.py", line 276, in cargo_list
    cargos = db.query(Cargo).options(joinedload(Cargo.train)).all()
                                     ^^^^^^^^^^
NameError: name 'joinedload' is not defined
